# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: annie
      POSTGRES_PASSWORD: annieMagicWord
      POSTGRES_DB: liquor
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U annie -d liquor"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  etl:
    build:
      context: ..
      dockerfile: docker/python/Dockerfile
    container_name: annie-etl
    depends_on:
      db:
        condition: service_healthy
      superset:
        condition: service_started
    environment:
      SALES_ENTRIES_LIMIT: 1_000_000
      POSTGRES_USER: annie
      POSTGRES_PASSWORD: annieMagicWord
      POSTGRES_DB: liquor
      POSTGRES_HOST: db
    volumes:
      - ../data:/app/data
      - ./superset/dashboards:/app/dashboards
  
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    depends_on:
      - db
    environment:
      - ADMIN_USERNAME=annie
      - ADMIN_PASSWORD=annieMagicWord
      - ADMIN_EMAIL=annie@gmail.com
    ports:
      - '8088:8088'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 2s
      retries: 2

volumes:
  postgres_data: